databases:
  - name: saif
    databaseName: saif_66mi
    user: saif_66mi_user
    plan: free

services:
  - type: web
    name: saif
    runtime: ruby
    plan: free
    buildCommand: "bundle install rails db:create rails db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: saif
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
